using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using UserApprovalApi.DTOs;
using UserApprovalApi.Services;

namespace UserApprovalApi.Controllers
{
    [ApiController]
    [Route("api/reports")]
    [Authorize(Roles = "Admin, Manager")]
    public class ReportsController : ControllerBase
    {
        private readonly IReportService _reportService;

        public ReportsController(IReportService reportService)
        {
            _reportService = reportService;
        }

        /// <summary>
        /// Get all reports (Admin/Manager only)
        /// </summary>
        [HttpGet]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GetAllReports(CancellationToken ct)
        {
            var reports = await _reportService.GetAllReportsAsync(ct);
            return Ok(reports);
        }

        /// <summary>
        /// Get filtered reports with pagination (Admin/Manager only)
        /// </summary>
        [HttpGet("filtered")]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GetFilteredReports([FromQuery] ReportFilterDto filter, CancellationToken ct)
        {
            var pagedResult = await _reportService.GetFilteredReportsAsync(filter, ct);
            return Ok(pagedResult);
        }

        /// <summary>
        /// Get report by ID
        /// </summary>
        [HttpGet("{id}")]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GetReportById(int id, CancellationToken ct)
        {
            var report = await _reportService.GetReportByIdAsync(id, ct);
            if (report == null)
                return NotFound(new { message = "Report not found" });

            return Ok(report);
        }

        /// <summary>
        /// Get reports generated by current user
        /// </summary>
        [HttpGet("my-reports")]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GetMyReports(CancellationToken ct)
        {
            var userId = User.FindFirstValue("nameid"); // Changed from "UserId" to "nameid"
            if (string.IsNullOrEmpty(userId))
                return Unauthorized(new { message = "User ID not found in token" });

            var reports = await _reportService.GetReportsByUserAsync(userId, ct);
            return Ok(reports);
        }

        /// <summary>
        /// Generate a new report (Admin/Manager can generate)
        /// </summary>
        [HttpPost("generate")]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> GenerateReport([FromBody] CreateReportDto createDto, CancellationToken ct)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var userId = User.FindFirstValue("nameid"); // Changed from "UserId" to "nameid"
            if (string.IsNullOrEmpty(userId))
                return Unauthorized(new { message = "User ID not found in token" });

            var report = await _reportService.GenerateReportAsync(createDto, userId, ct);
            return CreatedAtAction(nameof(GetReportById), new { id = report.Id }, report);
        }

        /// <summary>
        /// Delete a report (Admin/Manager can delete)
        /// </summary>
        [HttpDelete("{id}")]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> DeleteReport(int id, CancellationToken ct)
        {
            var success = await _reportService.DeleteReportAsync(id, ct);
            if (!success)
                return NotFound(new { message = "Report not found" });

            return Ok(new { message = "Report deleted successfully" });
        }
    }
}
